services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_STRAPI_URL=${NEXT_PUBLIC_STRAPI_URL:-http://api.borkssport.ru}
    container_name: sportmagazine-frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: "0.0.0.0"
      NEXT_PUBLIC_STRAPI_URL: ${NEXT_PUBLIC_STRAPI_URL:-http://api.borkssport.ru}
    ports:
      - '3000:3000'
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
    external: false

